import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";

const font = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Navbar />
        {children}
        </body>
    </html>
  );
}
