import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import TopBar from "./components/navbar/top-bar";
import Logo from "./components/navbar/logo";
import InputSearch from "./components/navbar/input-search";
import ComboBoxCate from "./components/navbar/combobox-cate";
import ActionButton from "./components/navbar/action-buttons";
import SelectCategory from "./components/navbar/select-category";
import NavigationBar from "./components/navbar/navigation-bar";
import BottomBar from "./components/bottombar/page";

import { ThemeProvider } from "@/components/ui/theme-provider"; // Import the ThemeProvider
import Footer from "./components/footer/Footer";

const font = Outfit({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "E-Commerce Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${font.className} bg-gray-100 dark:bg-gray-900`}>
        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        > 
          <div className="bg-gray-800 p-2.5 w-full px-4 md:px-6">
            <div className=" max-w-7xl mx-auto">
              <TopBar  />
            </div>
           
          </div>
          <div className="w-full z-40 sticky top-0 border-b px-5 bg-white dark:bg-black md:px-6 mx-auto py-3">
              <div className="max-w-7xl mx-auto justify-between items-center flex">
                <Logo />
                <div className='flex space-x-2'>
                  <InputSearch />
                  <ComboBoxCate />
                </div>
                <ActionButton />
              </div>
          </div>
          <div className="bg-white dark:bg-black border-b p-2.5 w-full hidden lg:block">
            <div className=" max-w-7xl mx-auto hidden lg:flex justify-between">
              <SelectCategory />
              <NavigationBar />
            </div>
          </div>
          {children}
          <Footer />
          <BottomBar />
        </ThemeProvider>
        </body>
    </html>
  );
}
